#!/bin/bash

export WINE=/usr/bin/wine
export SWINECLI=/usr/bin/swinecli
export SLOT=test
export WINETRICKS=/usr/bin/winetricks
export WINEPREFIX=$HOME/.swine/test
export TMP=/tmp

WISLIB=/usr/lib/swine/wislib

if [ -f "$WISLIB" ]; then
  . "$WISLIB"
elif [ -f "`dirname $0`/wislib" ]; then
  . "`dirname $0`/wislib"
else
  echo "Fatal: wislib not found" >&2
  exit -1
fi

if [ -f "$1" ]; then
  . $1
else
  echo "Fatal: script $1 not found" >&2
  exit -2
fi
