#!/bin/bash

export WINE="`which wine`"
export SWINECLI="`which swinecli`"
export WINETRICKS="`which winetricks`"
export TMP=/tmp

WISLIB=/usr/lib/swine/wislib

if [ -z "$SLOT" ]; then
  echo "Fatal: SLOT not set" >&2
  exit -1
fi  

if [ -f "$WISLIB" ]; then
  . "$WISLIB"
elif [ -f "`dirname $0`/wislib" ]; then
  . "`dirname $0`/wislib"
else
  echo "Fatal: wislib not found" >&2
  exit -1
fi

if [ -f "$1" ]; then
  . $1
else
  echo "Fatal: script $1 not found" >&2
  exit -2
fi
