#!/bin/bash

export WINE="`which wine`"
export SWINECLI="`which swinecli`"
export WINETRICKS="`which winetricks`"
export TMP=/tmp

WISLIB_DIRS=(/usr/lib/swine/wislib "`dirname $0`/wislib")
for file in "${WISLIB_DIRS[@]}"; do
  [ -f "$file" ] && WISLIB="$file"
done

if [ -f "$WISLIB" ]; then
  . "$WISLIB"
else
  echo "Fatal: wislib not found" >&2
  exit -1
fi

if [ -f "$1" ]; then
  . $1
else
  echo "Fatal: script $1 not found" >&2
  exit -2
fi
